sudo: required
services:
- docker
language: python
env:
  global:
  - IMAGE="bearn/docker-nginx-basic-auth"
  - REGISTRY_USER=bearn
  - secure: quwWy6EtAD8dgRWewK/uF4EChGtLCnKBB3/SRo8Vir8ZfEGqzjxY8g8fJac7s5wzKbl5pfC2H2J4Jfsvvc2cWeMNvffFllFV8gbTaU7bF/0/vVdeiEOLluDjAp6mgDijVKG3ZqTyr1NKN0VXNLBFeTOcbgzC4mWwNmwncl6dT6efcwk5CGNZvp4q8YqMOia5iEqMODMeZccaHAqGJDF3Iwxf88dZuQTVsE0SjabrR9NdLm7OInHcAKVuKAy2YU5637t7zgFGMM4UN2UPg3izmLOGA7tQYaP3c42HzwpDNw/EzKjZ/uyWtaH5PLEG/SSv7IQrKh0tY+iP8c/SefpRQfu4fgEBpjW7sX2UQpKrAHZOrnDCE8c4FcifMTDajXEwt8CbU8yGKCXIbARHAKpfk19jwYWtaDxEuBEF4GVOMabntMjUoQQA7r/x33KYQtZWssqAOSVC2lG72ZpkHrDZK0Jisxsg6/AMLtQjsHFyQHW3Gr1wauorAyEymQX1tdBVXnI5jHoOvY/lGDaPebayuLmk7wp/9hTsKIwqolZKfmV9lj0ZSfyoOQ0oJQn8zB5rrKM3c/idu8LiU6AVqlAKfXupF9ntVaBF6n+QBwuODfoENq5e/Un4Vmbu6v8xxWa8YVfvJxiguzfYvCNoey5/q05yXKzQP0wY+KWpGnVLROo=
before_install:
- sudo apt-get update
- sudo apt-get install -qy -o Dpkg::Options::="--force-confold" docker-ce
install: []
before_script:
- version="$(awk '$2 == "TAG_VERSION" { print $3; exit }' Dockerfile | cut -d'~' -f1)"
- docker pull "$IMAGE" || true
script:
- docker build --pull --cache-from "$IMAGE" -t "$IMAGE" .
before_deploy:
- pip install docker-ci-deploy==0.2.0
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
deploy:
  provider: script
  script: dcd --tag-version "$version" --tag-semver --tag-latest "$IMAGE"
  on:
    branch: master
